### ISSUE TITLE
how are non apple clients handled?

### ISSUE THREAD

**Issue by AndySchroder** [freswa/dovecot-xaps-daemon#10]
It is unclear in your documentation what happens with non apple phone users. Does this plugin send apple a notification for every single e-mail the dovecot server ever gets? If so, this seems like a major privacy issue for people who opted out of apple products in the first place.

If it only sends notifications to apple for people who have apple phones and are actively logged in with them, how is that communicated? Is there some message that goes through the IMAP connection that is then passed from dovecot to this plugin? If so, could you point to where this is at in the code?

**Comment by tgrushka** [comment]
My understanding (as a user of this plugin) is that xapsd only gets notified if a message recipient has registered their client for APNS in Dovecot. Also, the key sent to Apple has to be registered as a client, and I don't think the whole message is sent, just a "ping" that basically tells Apple Mail to download the message by its ID. Is this correct?
