### ISSUE TITLE
per user plugin activation possible?

### ISSUE THREAD

**Issue by AndySchroder** [freswa/dovecot-xaps-daemon#12]
Maybe an iOS user doesn't want apple to be notified every time they get an e-mail. Is it possible to allow or disallow this push notification plugin's capability for certain users? If so, would it be at a dovecot level or an access list baked into this plugin?

**Comment by freswa** [comment]
This is neither the issue tracker of the plugin nor a question and answer forum.
Feel free to fill _issue_ tickets here if you find bugs or would like to see features, but please use the search to check for existing/fixed/closed bugs and use other ways of communication (IRC/e-mail/whatever) if you need support.
