### ISSUE TITLE
Configuration question: HTTP request ports

### ISSUE THREAD

**Issue by FreelancerJay** [freswa/dovecot-xaps-daemon#15]
In the configuration, we have both 11619 and 11620 available.
Given 11619 appears in dovecot-xaps-plugin as where to send notifications to, is 11620 optional, or is it where client devices will connect to?

And in firewall setup, would I only allow connections to 11619 from the local system and not external systems, and 11620 from external systems, or if 11620 is in use should 11619 still be externally accessible?

**Comment by freswa** [comment]
11620 is optional. The client connects to IMAP only. Both ports are not made to be public available. Use them only on localhost for dovecot.

**Comment by FreelancerJay** [comment]
Thank you for the clarification.

And I should have started off saying thank you so much for making this fork of the xaps software set! I've now set it up on a testing mail server I'm playing with and it was a lot easier to do that the first time around a couple years ago.
I'm especially appreciative of the automatically renewing certificates being built in, I can finally retire my old El Capitan Mac!

The delivery of notifications from the plugin to the daemon via http is also a great touch, and allows me to throw away a old hacky unix socket over ssl tunnel from the backend mail store to the front end mail proxy, muuuuch nicer!
