### ISSUE TITLE
Can't build xapsd, dependencies broken?

### ISSUE THREAD

**Issue by lsergei** [freswa/dovecot-xaps-daemon#16]
Trying to build this daemon on CentOS 7 with Go 1.16.13 and getting following error:

`# go build ./cmd/xapsd

go: github.com/spf13/afero@v1.8.2 requires
	cloud.google.com/go/storage@v1.14.0 requires
	github.com/golang/protobuf@v1.4.3 requires
	google.golang.org/protobuf@v1.23.0 requires
	github.com/golang/protobuf@v1.4.0 requires
	google.golang.org/protobuf@v1.21.0 requires
	github.com/golang/protobuf@v1.4.0-rc.4.0.20200313231945-b860323f09d0: invalid version: git fetch --unshallow -f origin in /root/go/pkg/mod/cache/vcs/6e18cbff36266c74e48dd81b4b672026ac74fb69c838ddb6240f256bb8edf590: exit status 128:
	fatal: git fetch-pack: expected shallow list`

Previously I had build https://github.com/st3fan/dovecot-xaps-daemon many times with no issues.

I am not an expert in Go and quick googling didn't help so asking for advice here.

**Comment by freswa** [comment]
Could you try building with go >= 1.17? I had issues with lower versions and just [bumped the CI a couple of days ago](8cec7c82b69734c7f619c768825902a44db465b1)

**Comment by lsergei** [comment]
thank you @freswa - replaced go 1.16 with v18.1 and everything compiled well. 

We can close the issue
