### ISSUE TITLE
"Cannot open databasefile" every few days

### ISSUE THREAD

**Issue by freultwah** [freswa/dovecot-xaps-daemon#3]
FreeBSD 12.2.

xapsd only runs for a limited period of time, and then starts having issues with its database:

`DEBU[0000] Opening databasefile at /var/db/xapsd/database.json `
`FATA[0000] Cannot open databasefile: /var/db/xapsd/database.json `

Increasing loglevel to trace did not help get any extra information. Removing the database and generating a new certificate makes it run again. The certs used to be valid for a year. Has it changed to five days now or is the culprit elsewhere?

[Edit: Apple sent an e-mail about issuing a new certificate and it's indeed still valid for a year.]

**Comment by freswa** [comment]
That looks weird. Does the db file exist when the error occurs?

**Comment by freswa** [comment]
Could you please checkout eeb2c479bc6773622c42cd10a37613e6500cc5b9 which I just pushed? It makes the error printed when the db open fails more verbose.

**Comment by freultwah** [comment]
Yes, it does. It appears that while it runs, all is good, but should I restart the daemon after an N amount of time (haven't determined the timeframe, other obligations), it can no longer read the database. It's all fine for a while, restarts work and all. I just checked and it works on one machine where I created the certs on 03 November, and failed on another where they'd been created on 30 October.

**Comment by freswa** [comment]
Could you give me a broken db so that I can investigate it?

**Comment by freultwah** [comment]
Dropped an e-mail.

**Comment by freultwah** [comment]
DEBU[0000] Opening databasefile at /var/db/xapsd/database.json 
FATA[0000] Cannot open databasefile: json: cannot unmarshal number 22827901023206141279553219084487350886039787685275408823622870937740013594975510607584883912993301715916019204233344448781680422510147054435433323068213843511365844905255703747699332701476007985827702109865970608894302050608233587055940800289590505836939605009083717241871417696204449691617047640758268786510605611644763575192281858843529538082096433227655691682459143769059471803884364933816784953050095187822075710649101634678726063256044863146101299043454486497573446327105441018344150112538591593871741215760668612223150463290617311970835379701085748127244106940691073605456420407886647310617100400703263525826269 into Go struct field Certificate.AppleCerts.Signature.PrivateKey of type float64

**Comment by freswa** [comment]
Thank you, just go the same error msg. Will look into it now :)

**Comment by freswa** [comment]
If you want to continue using any existing db, you just have to replace all `PrivateKey:{...}` ocurrences with `PrivateKey: null`

**Comment by freultwah** [comment]
I am afraid I'd already jumped the gun. No harm done, though. Thanks for finding and fixing it. I also updated my dovecot-xaps FreeBSD ports repo, should anybody at all be interested in the functionality.
