### ISSUE TITLE
Follow debug settings from dovecot (minor)

### ISSUE THREAD

**Issue by HQuest** [freswa/dovecot-xaps-daemon#30]
Can the plugin code be updated to reflect dovecot's debug/verbose/info configurations before add debug messages at the logs, instead of blindly calling i_debug functions at certain steps?

**Comment by freswa** [comment]
In general yes, but it's not trivial since the `e_debug` function is called on events and we don't have events available for all `e_debug` calls. But things can be worked on if someone is willing to sponsor it.

**Comment by HQuest** [comment]
... never mind, I was supposed to place this request into the plugin repo, not the daemon.
