### ISSUE TITLE
Is there a mistake in VendorCerts usage?

### ISSUE THREAD

**Issue by kjarex** [freswa/dovecot-xaps-daemon#33]
As far as I can see (and think to understand) only the first 9 of the 10 vendorCerts are being used (only [here](https://github.com/freswa/dovecot-xaps-daemon/blob/c47d6654222e3328e5d7314f25b619dbc4e06233/pkg/apple_xserver_certs/request.go#L116) as `Intn(9)` would result in numbers from 0 to 8, ergo only the first 9 of the array)

This isn't an issue as in "it will/ might not work" but I assume it's not as it was intended (as I can't see the 10th cert being used anywhere else either)

**Comment by freswa** [comment]
Thanks for the report. *Someone* didn't read the docs correctly:
`Intn returns, as an int, a non-negative pseudo-random number in the half-open interval [0,n) from the default Source. It panics if n <= 0.`
Fix incoming.
