### ISSUE TITLE
Run daemon but as port listener instead of socket

### ISSUE THREAD

**Issue by barart** [freswa/dovecot-xaps-daemon#34]
If is possible to run the daemon to listen a port instead a socket file? I have multiple servers and im thinking that, instead of running the daemon on every server, just run the daemon on one server and configure the plugin on the others servers to send the notifications to that server instead of local socket

**Comment by freultwah** [comment]
It does listen on a port, 11619 by default. 

from xapsd.yaml:

# This sets the address and port number of the listen socket.
listenAddr: '[::1]'
port: 11619

Excerpt from the plugin config:

xaps_config = url=http://localhost:11619

Change as you see fit.

**Comment by barart** [comment]
Excellent 👌🏻👌🏻 and, can I restrict ip's or only allow certain ip's?

**Comment by freswa** [comment]
No. You may restrict IPs in your firewall though.
