### ISSUE TITLE
context deadline exceeded

### ISSUE THREAD

**Issue by darylrichards** [freswa/dovecot-xaps-daemon#35]
For the last while, the push daemon dies regularly on me, with the error:

`level=fatal msg="Error:Post \"https://api.push.apple.com/3/device/xxxxxx\": context deadline exceeded"`

I've tried looking through the code and putting debugging info around every http call and can't find anything as yet..

Any ideas?

**Comment by freswa** [comment]
This is basically a timeout. Looks to me like you ran into some rate limiting.

**Comment by darylrichards** [comment]
This happens pretty much all the time, and the program crashes. Is there a way to get it gracefully continue?

**Comment by freswa** [comment]
Could you provide full debug logs please?

**Comment by darylrichards** [comment]
Okay, now you got me.. I have `loglevel: debug` set, but I don't get any more messages than that line. Do the debug logs go somewhere funky?

**Comment by darylrichards** [comment]
Even just running it on command line:

```
root@lagoon:/var/log# xapsd
INFO[0000] Certificate valid until 2024-03-12 14:17:34 +0000 UTC
WARN[0006] No registration found for username: daryl@isletech.net
WARN[0069] No registration found for username: daryl@isletech.net
WARN[0076] No registration found for username: daryl@isletech.net
WARN[0078] No registration found for username: daryl@isletech.net
WARN[0078] No registration found for username: daryl@isletech.net
FATA[0195] Error:Post "https://api.push.apple.com/3/device/xxxxx": context deadline exceeded
```

**Comment by darylrichards** [comment]
So, evidently on FreeBSD, even though the command line points the config at /usr/local/etc/xapsd/xapsd.yaml, the software ignores that and uses /etc/xapsd/xapsd.yaml anyways..

`
DEBU[0283] Found registration F0220481-8A1D-4A28-BE48-EA13B0CD3028 with token 2CA8A8624D45D0605F8E88EF9E2F10D0433A8F44A26356FC905F721149CB15EA for username: daryl@isletech.net 
DEBU[0283] Sending notification to F0220481-8A1D-4A28-BE48-EA13B0CD3028 / 2CA8A8624D45D0605F8E88EF9E2F10D0433A8F44A26356FC905F721149CB15EA 
DEBU[0283] Sending: {"aps":{"account-id":"F0220481-8A1D-4A28-BE48-EA13B0CD3028"}} 
DEBU[0283] Ignoring non INBOX event for: Sent           
DEBU[0293] Found registration F0220481-8A1D-4A28-BE48-EA13B0CD3028 with token 2CA8A8624D45D0605F8E88EF9E2F10D0433A8F44A26356FC905F721149CB15EA for username: daryl@isletech.net 
DEBU[0293] Sending notification to F0220481-8A1D-4A28-BE48-EA13B0CD3028 / 2CA8A8624D45D0605F8E88EF9E2F10D0433A8F44A26356FC905F721149CB15EA 
DEBU[0293] Sending: {"aps":{"account-id":"F0220481-8A1D-4A28-BE48-EA13B0CD3028"}} 
DEBU[0300] Checking all delayed APNS                    
FATA[0303] Error:Post "https://api.push.apple.com/3/device/2CA8A8624D45D0605F8E88EF9E2F10D0433A8F44A26356FC905F721149CB15EA": context deadline exceeded `

**Comment by freultwah** [comment]
The port apparently does not sed that particular string in ${WRKSRC}/internal/config/config.go. In [my own port](https://github.com/freultwah/dovecot-xaps-daemon-freebsd) that predates the one in FreeBSD ports tree, I have:

```
post-patch:
        @${REINPLACE_CMD} -e 's|etc\/xapsd|usr\/local\/etc\/xapsd|' ${WRKSRC}/internal/config/config.go
        @${REINPLACE_CMD} -e 's|var\/lib|var\/db|' ${WRKSRC}/configs/xapsd/xapsd.yaml
        @${REINPLACE_CMD} -e 's|var\/run\/dovecot|var\/run\/xapsd|' ${WRKSRC}/configs/xapsd/xapsd.yaml
```

I think the port maintainer should be contacted,

**Comment by freswa** [comment]
As far as I understand you're running into a timeout here. Since I cannot reproduce this on multiple systems, it seems to be an infrastructural issue either on the network or on the OS side.

**Comment by darylrichards** [comment]
I would say my biggest thing, is having the software log an error and then continue, not die completely.
