### ISSUE TITLE
go version nightmare

### ISSUE THREAD

**Issue by HQuest** [freswa/dovecot-xaps-daemon#38]
Trying to recompile xapsd, go is a nightmare. xapsd requires go 1.19.7, module exp/constraints requires go 1.20. However go 1.20 and newer produces a buggy code (as confirmed on README file), and gcc-go doesn't work as it is based on go 1.18.

Aren't Python or C# options for a less volatile language? Absolutely anything Google related is a hit, miss, or an ad, and these days, Hartley any hits.

**Comment by freswa** [comment]
So what's the issue here?

> Aren't Python or C# options for a less volatile language?

Python is a bit more fragile due to it's runtime dependencies. Go is more or less statically linked.
I haven't done any C#, but feel free to give it a go. If someone wants to rewrite the code in rust or sponsor the work, I'm down for it.

**Comment by freultwah** [comment]
> Trying to recompile xapsd, go is a nightmare. xapsd requires go 1.19.7, module exp/constraints requires go 1.20. However go 1.20 and newer produces a buggy code (as confirmed on README file), and gcc-go doesn't work as it is based on go 1.18.

FreeBSD has included [this patch](https://github.com/freswa/dovecot-xaps-daemon/pull/36/commits/1c52af3a7cc168cec089a810c32e861ab988840c) for the time being. Works with Go 1.20+.

**Comment by freultwah** [comment]
> > Trying to recompile xapsd, go is a nightmare. xapsd requires go 1.19.7, module exp/constraints requires go 1.20. However go 1.20 and newer produces a buggy code (as confirmed on README file), and gcc-go doesn't work as it is based on go 1.18.
> 
> FreeBSD has included [this patch](https://github.com/freswa/dovecot-xaps-daemon/pull/36/commits/1c52af3a7cc168cec089a810c32e861ab988840c) for the time being. Works with Go 1.20+.

Until it did not. I had 7000+ notifications from one single machine stating that the certificate is about to expire. Attempts at renewal were apparently not successful.

**Comment by freswa** [comment]
Fixed with #36
