### ISSUE TITLE
Issues with loading settings from xapsd.yaml

### ISSUE THREAD

**Issue by jonoz** [freswa/dovecot-xaps-daemon#8]
The default /etc/xapsd/xapsd.yaml doesn't seem to get loaded correctly when running xapsd without any command line options:

FATA[0000] not a valid logrus Level: ""

It appears that the loglevel value is empty "".  Other settings (databaseFile in particular) failed to load as well, except the "appleId" settings since the apns certificate request/generation worked at some point.

I'm using the default xapsd.yaml as is, the only settings I'm interested in changing is the loglevel. "databaseFile" failed to load after hard coding "loglevel", so something is odd with loading of the config.

I am able to work around the issue by hard coding all the various offending settings.

This is running on a fresh Debian 10 install.  Could be environmental but I'm not sure.

**Comment by freswa** [comment]
Could you please paste your `/etc/xapsd/xapsd.yaml`? I just recompiled v1.0 and can't reproduce.

**Comment by jonoz** [comment]
# set the loglevel to either
# trace, debug, error, fatal, info, panic or warn
# Default: warn
loglevel: info

# xapsd creates a json file to store the registration persistent on disk.
# This sets the location of the file.
databaseFile: /var/lib/xapsd/database.json

# xapsd listens ona a socket for http/https requests from the dovecot plugin. This sets the port number of the socket.
port: 11619

# xapsd is able to listen on a HTTPS Socket to allow HTTP/2 to be used
# SSL is enabled implicitly when certfile and keyfile exist
# !!! only use HTTPS for connection pooling with a proxy e.g. nginx or HaProxy
# !!! direct usage with the plugin is discouraged and unsupported
tlsCertfile:
tlsKeyfile:
tlsPort: 11620

# Notifications that are not initiated by new messages are not sent immediately for two reasons:
# 1. When you move/copy/delete messages you most likely move/copy/delete more messages within a short period of time.
# 2. You don't need your mailboxes to synchronize immediately since they are automatically synchronized when opening
#    the app
# If a new message comes and the move/copy/delete notification is still on hold it will be sent with the notification
# for the new message.
# This sets the interval to check for delayed messages.
checkInterval: 20

# Set the time how long notifications for not-new messages should be delayed until they are sent.
# Whenever checkInterval runs, it checks if "delay" <= "waiting time" and sends the notification if the expression is
# true.
delay: 30

# To retrieve certificates from Apple, we need to login with a valid Apple ID
# The accounts email must be given in cleartext, but the password has to
# be hashed before sending it. To not leak working credentials on running servers,
# we do not accept the cleartext password here.
appleId: ***

# use `xaps -pass` to calculate the hash of the apple id password
appleIdHashedPassword: ***

**Comment by jonoz** [comment]
```
# set the loglevel to either
# trace, debug, error, fatal, info, panic or warn
# Default: warn
loglevel: info

# xapsd creates a json file to store the registration persistent on disk.
# This sets the location of the file.
databaseFile: /var/lib/xapsd/database.json

# xapsd listens ona a socket for http/https requests from the dovecot plugin. This sets the port number of the socket.
port: 11619

# xapsd is able to listen on a HTTPS Socket to allow HTTP/2 to be used
# SSL is enabled implicitly when certfile and keyfile exist
# !!! only use HTTPS for connection pooling with a proxy e.g. nginx or HaProxy
# !!! direct usage with the plugin is discouraged and unsupported
tlsCertfile:
tlsKeyfile:
tlsPort: 11620

# Notifications that are not initiated by new messages are not sent immediately for two reasons:
# 1. When you move/copy/delete messages you most likely move/copy/delete more messages within a short period of time.
# 2. You don't need your mailboxes to synchronize immediately since they are automatically synchronized when opening
#    the app
# If a new message comes and the move/copy/delete notification is still on hold it will be sent with the notification
# for the new message.
# This sets the interval to check for delayed messages.
checkInterval: 20

# Set the time how long notifications for not-new messages should be delayed until they are sent.
# Whenever checkInterval runs, it checks if "delay" <= "waiting time" and sends the notification if the expression is
# true.
delay: 30

# To retrieve certificates from Apple, we need to login with a valid Apple ID
# The accounts email must be given in cleartext, but the password has to
# be hashed before sending it. To not leak working credentials on running servers,
# we do not accept the cleartext password here.
appleId: ***

# use `xaps -pass` to calculate the hash of the apple id password
appleIdHashedPassword: ***
```

**Comment by freswa** [comment]
Still works for me...
What go compiler version do you use?

**Comment by jonoz** [comment]
```go version go1.16.3 linux/amd64```

As I mentioned, could be environmental, figuring out what is the challenge.

Any suggestions on where to look would be useful.  Permissions to files, etc., it's running as xapsd:xapsd as per the suggestions in configs.

**Comment by freswa** [comment]
It reads *some* file successfully, otherwise xapsd wouldn't start at all. Do you have any additional config files laying around in /etc/xapsd? Can you move the original /etc/xapsd/xapsd.yaml to a different location and check if xapsd fails to start for you in this case?

**Comment by jonoz** [comment]
go.mod

```
require (
	github.com/freswa/go-plist v0.0.0-20201008215444-900e8a7d907d
	github.com/julienschmidt/httprouter v1.3.0
	github.com/sideshow/apns2 v0.20.0
	github.com/sirupsen/logrus v1.7.0
	github.com/spf13/viper v1.7.1
+	github.com/stretchr/objx v0.1.1 // indirect
	golang.org/x/net v0.0.0-20201224014010-6772e930b67b
)
```
Would ```github.com/stretchr/objx v0.1.1 // indirect``` be the culprit?

This was introduced at some point, I didn't touch go.mod directly.

**Comment by freswa** [comment]
I can't support any modified version of xapsd - sorry. Please compile the repo code and report back the behavior of xapsd as I requested above. Thank you :)

**Comment by jonoz** [comment]
I didn't add ```github.com/stretchr/objx```, not sure if it was introduced by the Go build process in pulling down updates, etc.  

The issues seem to be with the file ```/etc/xapsd/xapsd.json```, this was the database file from the original code that I was testing, before I came across your fork.

It's working now, learnt something today.

Apologies for the red herring. 🤦🏻‍♂️

**Comment by freswa** [comment]
No worries, great it's working for you now :)

**Comment by jonoz** [comment]
Just to clarify, the presence of `/etc/xapsd/xapsd.json` appears to have broken the loading of ```xapsd.yaml```, not sure if this was how it's designed - i.e. preferring `.json` config file or something along those line.

Might be worth looking into if you are keen.

Thanks again for helping out, I'm a happy camper now.  Keep up the good work!
